kind = "mobile"
previewPath = "/"
title = "Project P.R.F"
version = "1.0.0"
id = "artifacts/prf-app"
router = "expo-domain"

[[services]]
name = "expo"
ensurePreviewReachable = "/status"
paths = [ "/" ]
localPort = 18849

[services.development]
run = "pnpm --filter @workspace/prf-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/prf-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/prf-app", "run", "serve" ]

[services.env]
PORT = "18849"
BASE_PATH = "/"
