import type { Simulado } from './types';

export const MOCK_SIMULADOS: Simulado[] = [
  {
    id: 'sim-portugues',
    title: 'Simulado — Língua Portuguesa',
    description: 'Interpretação de texto, concordância, crase e regência',
    subject: 'portugues',
    timeLimit: 20,
    questions: [
      {
        id: 'sp1',
        text: 'Julgue: "Fazem dois anos que o agente ingressou na Polícia Rodoviária Federal."',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. "Fazer" indicando tempo decorrido é impessoal — fica no singular: "Faz dois anos".',
        subject: 'portugues',
      },
      {
        id: 'sp2',
        text: 'Julgue: "Havia muitos veículos irregulares na rodovia durante a blitz da PRF."',
        options: ['Certo', 'Errado'],
        correctIndex: 0,
        explanation: 'CERTO. "Haver" no sentido de "existir" é impessoal e permanece no singular. "Havia" é o correto.',
        subject: 'portugues',
      },
      {
        id: 'sp3',
        text: 'Assinale a alternativa com crase CORRETA:',
        options: [
          'O policial foi à realizar o teste.',
          'O policial foi à delegacia registrar o ocorrido.',
          'O policial referiu-se à ela no relatório.',
          'O policial chegou à pé na ocorrência.',
        ],
        correctIndex: 1,
        explanation: '"À delegacia" — substantivo feminino com artigo definido precedido de preposição. As demais estão erradas: antes de verbo (realizar), pronome (ela) e palavra masculina (pé) nunca se usa crase.',
        subject: 'portugues',
      },
      {
        id: 'sp4',
        text: 'Julgue: "O projeto de lei visa garantir maior segurança nas estradas federais." (uso do verbo VISAR)',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. "Visar" no sentido de "ter como objetivo" é transitivo indireto e exige preposição "a": "visa a garantir" ou "visa à garantia". Sem a preposição, o uso está incorreto na norma culta.',
        subject: 'portugues',
      },
      {
        id: 'sp5',
        text: 'Considere: "A situação onde o policial se encontrava era de extremo risco." O uso do pronome relativo "onde" está:',
        options: [
          'Correto, pois "onde" equivale a "em que"',
          'Incorreto — "onde" só se aplica a lugar físico; o correto seria "em que"',
          'Correto, pois "situação" pode ser considerada um espaço abstrato',
          'Incorreto — o correto seria "aonde"',
        ],
        correctIndex: 1,
        explanation: '"Onde" refere-se a lugar físico real. "Situação" é substantivo abstrato, portanto o relativo correto é "em que". "Aonde" só é usado com verbos que indicam movimento em direção a lugar.',
        subject: 'portugues',
      },
      {
        id: 'sp6',
        text: 'Julgue: A conjunção "embora" indica relação de concessão — introduz uma oração que admite o que foi dito na principal, sem, entretanto, negar a conclusão.',
        options: ['Certo', 'Errado'],
        correctIndex: 0,
        explanation: 'CERTO. "Embora" é conjunção concessiva. Ex: "Embora chovesse, a blitz prosseguiu." A chuva (concessão) não impediu a blitz (conclusão).',
        subject: 'portugues',
      },
      {
        id: 'sp7',
        text: 'Julgue: "Prefiro patrulhar rodovias mais que trabalhar em delegacia." — A frase está correta segundo a norma culta.',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. "Preferir" na norma culta exige a preposição "a", não "mais que": "Prefiro patrulhar rodovias a trabalhar em delegacia." O uso de "mais que" é incorreto com "preferir".',
        subject: 'portugues',
      },
      {
        id: 'sp8',
        text: 'Texto: "Embora o número de acidentes tenha caído, a imprudência dos condutores ainda preocupa os especialistas." Julgue: O texto afirma que a imprudência aumentou nos últimos anos.',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. O texto não afirma que a imprudência aumentou — apenas que ainda preocupa. Inferir "aumento" extrapola o que o fragmento afirma. Nunca inclua informações que o texto não forneceu.',
        subject: 'portugues',
      },
      {
        id: 'sp9',
        text: 'Julgue: "Houveram muitas ocorrências de embriaguez ao volante durante o feriadão." O verbo "houveram" está corretamente flexionado.',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. "Haver" no sentido de "existir/ocorrer" é impessoal — fica sempre no singular: "Houve muitas ocorrências". "Muitas ocorrências" é objeto direto, não sujeito.',
        subject: 'portugues',
      },
      {
        id: 'sp10',
        text: 'Qual conectivo preenche corretamente a lacuna? "O condutor estava em alta velocidade ______ o limite permitido era de 80 km/h."',
        options: ['logo', 'portanto', 'embora', 'pois'],
        correctIndex: 2,
        explanation: '"Embora" (concessivo) é o conectivo correto: ele indica que a velocidade era alta apesar do limite ser de 80 km/h. "Logo" e "portanto" são conclusivos. "Pois" é causal.',
        subject: 'portugues',
      },
    ],
  },
  {
    id: 'sim-rlm',
    title: 'Simulado — Raciocínio Lógico',
    description: 'Lógica proposicional, probabilidade e combinatória',
    subject: 'rlm',
    timeLimit: 25,
    questions: [
      {
        id: 'srl1',
        text: 'A proposição "Se o condutor está alcoolizado, então a PRF o autuará" é equivalente à:',
        options: [
          'Se a PRF autuou, então estava alcoolizado.',
          'Se a PRF não autuou, então não estava alcoolizado.',
          'Se o condutor não estava alcoolizado, então não será autuado.',
          'O condutor está alcoolizado e a PRF não o autuará.',
        ],
        correctIndex: 1,
        explanation: 'A contrapositiva de (p → q) é (¬q → ¬p) e é equivalente à original. "Se a PRF não autuou (¬q), então não estava alcoolizado (¬p)" é a contrapositiva correta.',
        subject: 'rlm',
      },
      {
        id: 'srl2',
        text: 'Qual é a negação correta de: "Todos os condutores alcoolizados são multados"?',
        options: [
          'Nenhum condutor alcoolizado é multado.',
          'Algum condutor alcoolizado não é multado.',
          'Todos os condutores alcoolizados não são multados.',
          'Algum condutor não alcoolizado é multado.',
        ],
        correctIndex: 1,
        explanation: 'A negação de "Todo A é B" é "Algum A não é B". Portanto: "Algum condutor alcoolizado não é multado."',
        subject: 'rlm',
      },
      {
        id: 'srl3',
        text: 'Em uma blitz, 30% dos veículos têm irregularidade. Selecionando 1 veículo aleatoriamente, qual a probabilidade de NÃO ter irregularidade?',
        options: ['30%', '60%', '70%', '40%'],
        correctIndex: 2,
        explanation: 'P(irregularidade) = 0,30. P(sem irregularidade) = 1 − 0,30 = 0,70 = 70%. É o complemento do evento.',
        subject: 'rlm',
      },
      {
        id: 'srl4',
        text: 'Uma equipe da PRF tem 6 agentes e precisa selecionar 2 para representar a unidade. De quantas formas isso pode ser feito (sem considerar a ordem)?',
        options: ['30', '15', '12', '36'],
        correctIndex: 1,
        explanation: 'Combinação C(6,2) = 6! / (2! × 4!) = (6 × 5) / (2 × 1) = 30 / 2 = 15 formas.',
        subject: 'rlm',
      },
      {
        id: 'srl5',
        text: 'O número de acidentes em uma rodovia aumentou 25% em 2024 em relação a 2023. Se em 2023 foram 200 acidentes, quantos ocorreram em 2024?',
        options: ['225', '240', '250', '255'],
        correctIndex: 2,
        explanation: '200 × 1,25 = 250 acidentes. Aumento de 25%: multiplica-se por (1 + 0,25) = 1,25.',
        subject: 'rlm',
      },
      {
        id: 'srl6',
        text: 'Julgue: O condicional (p → q) é FALSO apenas quando p é verdadeiro e q é falso.',
        options: ['Certo', 'Errado'],
        correctIndex: 0,
        explanation: 'CERTO. É a definição da tabela verdade do condicional: p→q é falso exclusivamente quando o antecedente (p) é verdadeiro e o consequente (q) é falso. Nas demais combinações, é verdadeiro.',
        subject: 'rlm',
      },
      {
        id: 'srl7',
        text: 'Quantos anagramas tem a palavra "RADAR"?',
        options: ['120', '30', '60', '20'],
        correctIndex: 1,
        explanation: 'RADAR tem 5 letras com A repetido 2 vezes e R repetido 2 vezes: 5! / (2! × 2!) = 120 / 4 = 30 anagramas.',
        subject: 'rlm',
      },
      {
        id: 'srl8',
        text: 'Em um sorteio, a probabilidade de ganhar é 1/5. Qual é a probabilidade de perder?',
        options: ['4/5', '1/4', '3/5', '2/5'],
        correctIndex: 0,
        explanation: 'P(perder) = 1 − P(ganhar) = 1 − 1/5 = 4/5. Princípio do complemento.',
        subject: 'rlm',
      },
    ],
  },
  {
    id: 'sim-ctb',
    title: 'Simulado — Legislação de Trânsito',
    description: 'CTB: normas, infrações, crimes e habilitação',
    subject: 'ctb',
    timeLimit: 20,
    questions: [
      {
        id: 'sctb1',
        text: 'Julgue: Um condutor que acumula 20 pontos na CNH em 12 meses terá sua habilitação automaticamente suspensa pelo DETRAN.',
        options: ['Certo', 'Errado'],
        correctIndex: 0,
        explanation: 'CERTO. O art. 261 do CTB estabelece a suspensão da habilitação ao acumular 20 ou mais pontos em 12 meses consecutivos.',
        subject: 'ctb',
      },
      {
        id: 'sctb2',
        text: 'Qual é a velocidade máxima permitida para automóveis em rodovias federais?',
        options: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'],
        correctIndex: 2,
        explanation: '110 km/h para automóveis em rodovias. Motos, ônibus e caminhões têm limite de 90 km/h nas rodovias.',
        subject: 'ctb',
      },
      {
        id: 'sctb3',
        text: 'O uso de celular ao volante é infração de que natureza e com qual multiplicador de multa?',
        options: [
          'Grave — sem multiplicador',
          'Gravíssima — multa × 2',
          'Gravíssima — multa × 3',
          'Média — multa × 2',
        ],
        correctIndex: 2,
        explanation: 'Art. 252, IX do CTB: usar celular ao volante é infração GRAVÍSSIMA com multa multiplicada por 3 (× 3).',
        subject: 'ctb',
      },
      {
        id: 'sctb4',
        text: 'No crime de embriaguez ao volante (art. 306 CTB), qual é o limite mínimo de concentração de álcool no ar alveolar para caracterização do crime?',
        options: ['0,05 mg/L', '0,1 mg/L', '0,2 mg/L', '0,3 mg/L'],
        correctIndex: 3,
        explanation: '0,3 mg/L de álcool por litro de ar alveolar é o limite para crime (art. 306 CTB). O limite administrativo (infração) é 0,05 mg/L.',
        subject: 'ctb',
      },
      {
        id: 'sctb5',
        text: 'O condutor que dirige disputando um racha (art. 308 CTB), sem resultado lesão ou morte, incorre em pena de:',
        options: [
          'Detenção de 6 meses a 1 ano',
          'Detenção de 1 a 3 anos',
          'Reclusão de 3 a 6 anos',
          'Apenas multa administrativa',
        ],
        correctIndex: 1,
        explanation: 'Art. 308 CTB: participar de racha (sem resultado lesão grave ou morte) — detenção de 1 a 3 anos. Se houver lesão grave: 3 a 6 anos. Se resultar morte: 5 a 10 anos.',
        subject: 'ctb',
      },
      {
        id: 'sctb6',
        text: 'Julgue: A recusa do condutor em realizar o teste do etilômetro não acarreta penalidade alguma, pois é um direito constitucional não autoincriminar-se.',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. A recusa ao etilômetro é infração GRAVÍSSIMA (art. 165-A do CTB) com multa × 3, retenção do veículo e suspensão imediata do direito de dirigir — as mesmas penalidades da embriaguez comprovada.',
        subject: 'ctb',
      },
      {
        id: 'sctb7',
        text: 'Em um cruzamento sem sinalização, qual veículo tem preferência de passagem?',
        options: [
          'O veículo maior',
          'O veículo que chegou primeiro',
          'O veículo que vem pela direita do outro',
          'O veículo que estiver em via pavimentada',
        ],
        correctIndex: 2,
        explanation: 'Art. 29, III, a do CTB: em cruzamentos sem sinalização, tem preferência o veículo que vem pela direita do outro condutor.',
        subject: 'ctb',
      },
      {
        id: 'sctb8',
        text: 'Qual é a pena para o crime de homicídio culposo na direção de veículo automotor (art. 302 CTB)?',
        options: [
          'Reclusão de 1 a 3 anos',
          'Detenção de 2 a 4 anos',
          'Reclusão de 2 a 4 anos',
          'Detenção de 6 meses a 2 anos',
        ],
        correctIndex: 1,
        explanation: 'Art. 302 CTB: homicídio culposo na direção — detenção de 2 a 4 anos. A pena pode ser aumentada se o condutor estava embriagado, em racha ou em excesso de velocidade.',
        subject: 'ctb',
      },
    ],
  },
  {
    id: 'sim-constitucional',
    title: 'Simulado — Dir. Constitucional e Administrativo',
    description: 'CF/88, princípios LIMPE, atos administrativos e licitações',
    subject: 'constitucional',
    timeLimit: 25,
    questions: [
      {
        id: 'sca1',
        text: 'Julgue: O habeas corpus é o remédio constitucional adequado para proteger o direito de acesso a informações pessoais constantes em banco de dados público.',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. O remédio adequado é o HABEAS DATA (art. 5º, LXXII), que visa assegurar o conhecimento e retificação de informações pessoais em bancos de dados governamentais. Habeas Corpus tutela a liberdade de locomoção.',
        subject: 'constitucional',
      },
      {
        id: 'sca2',
        text: 'O princípio da eficiência foi inserido na Constituição Federal por qual emenda?',
        options: ['EC 19/1998', 'EC 41/2003', 'EC 45/2004', 'EC 32/2001'],
        correctIndex: 0,
        explanation: 'A EC 19/1998 (Reforma Administrativa) inseriu o princípio da Eficiência no caput do art. 37 da CF/88, tornando LIMPE o acrônimo completo dos cinco princípios expressos.',
        subject: 'constitucional',
      },
      {
        id: 'sca3',
        text: 'Julgue: A Administração Pública pode revogar um ato administrativo por razões de ilegalidade, com efeito ex tunc (retroativo).',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. REVOGAÇÃO ocorre por razões de conveniência/oportunidade (mérito), com efeito ex nunc. ANULAÇÃO ocorre por ilegalidade, com efeito ex tunc. O enunciado confundiu os dois institutos.',
        subject: 'administrativo',
      },
      {
        id: 'sca4',
        text: 'Qual modalidade de licitação prevista na Lei 14.133/2021 é OBRIGATÓRIA para aquisição de bens e serviços comuns?',
        options: ['Concorrência', 'Tomada de Preços', 'Pregão', 'Leilão'],
        correctIndex: 2,
        explanation: 'O Pregão é a modalidade obrigatória para bens e serviços comuns, preferencialmente eletrônico, conforme a Lei 14.133/2021. A Tomada de Preços foi extinta pela nova lei.',
        subject: 'administrativo',
      },
      {
        id: 'sca5',
        text: 'A PRF tem competência constitucional para atuar em qual tipo de via?',
        options: [
          'Vias estaduais e federais',
          'Apenas rodovias e estradas federais',
          'Qualquer via pública do país',
          'Vias federais e municipais',
        ],
        correctIndex: 1,
        explanation: 'Art. 144, II da CF/88: a PRF destina-se ao patrulhamento ostensivo das rodovias federais. Sua competência territorial é restrita às vias FEDERAIS.',
        subject: 'constitucional',
      },
      {
        id: 'sca6',
        text: 'Julgue: O princípio da legalidade para a Administração Pública significa que ela pode fazer tudo o que a lei não proibir expressamente.',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO. Para a Administração, legalidade significa que ela só pode fazer o que a lei AUTORIZA (vinculação positiva à lei). Para o particular, legalidade significa poder fazer o que a lei não proibir. São sentidos opostos do princípio.',
        subject: 'administrativo',
      },
      {
        id: 'sca7',
        text: 'Qual remédio constitucional pode ser impetrado por qualquer cidadão para anular ato lesivo ao patrimônio público?',
        options: ['Mandado de Segurança', 'Habeas Data', 'Ação Popular', 'Mandado de Injunção'],
        correctIndex: 2,
        explanation: 'A Ação Popular (art. 5º, LXXIII) pode ser impetrada por qualquer cidadão (eleitor) para anular ato lesivo ao patrimônio público, à moralidade administrativa, ao meio ambiente e ao patrimônio histórico-cultural.',
        subject: 'constitucional',
      },
      {
        id: 'sca8',
        text: 'Julgue: A contratação de empresa com fornecimento exclusivo de um produto é caso de inexigibilidade de licitação, e não de dispensa.',
        options: ['Certo', 'Errado'],
        correctIndex: 0,
        explanation: 'CERTO. Na inexigibilidade (art. 74 da Lei 14.133/2021), a competição é inviável por natureza — como no caso de fornecedor exclusivo. Na dispensa, a competição seria possível mas a lei a dispensa. Fornecedor exclusivo = inexigibilidade.',
        subject: 'administrativo',
      },
    ],
  },
  {
    id: 'sim-misto',
    title: 'Simulado Misto — PRF',
    description: 'Questões de todas as matérias do edital PRF',
    subject: 'misto',
    timeLimit: 30,
    questions: [
      {
        id: 'sm1',
        text: 'Julgue: "Haviam muitos veículos na rodovia durante a operação Carnaval da PRF."',
        options: ['Certo', 'Errado'],
        correctIndex: 1,
        explanation: 'ERRADO (Português). "Haver" no sentido de existir é impessoal. O correto é "Havia muitos veículos".',
        subject: 'portugues',
      },
      {
        id: 'sm2',
        text: 'Qual é a pena para o crime de embriaguez ao volante (art. 306 do CTB)?',
        options: ['6 meses a 1 ano', '6 meses a 3 anos', '1 a 3 anos', '2 a 4 anos'],
        correctIndex: 1,
        explanation: 'Art. 306 CTB: embriaguez ao volante — detenção de 6 meses a 3 anos, mais multa e suspensão.',
        subject: 'ctb',
      },
      {
        id: 'sm3',
        text: 'A negação lógica de "Todos os agentes da PRF são eficientes" é:',
        options: [
          'Nenhum agente da PRF é eficiente.',
          'Algum agente da PRF não é eficiente.',
          'Todos os agentes da PRF não são eficientes.',
          'Algum agente da PRF é eficiente.',
        ],
        correctIndex: 1,
        explanation: '(RLM) A negação de "Todo A é B" é "Algum A não é B".',
        subject: 'rlm',
      },
      {
        id: 'sm4',
        text: 'A Declaração Universal dos Direitos Humanos foi proclamada em:',
        options: ['10/12/1945', '10/12/1948', '10/12/1950', '26/06/1945'],
        correctIndex: 1,
        explanation: 'A DUDH foi proclamada pela ONU em 10 de dezembro de 1948 — Dia Internacional dos Direitos Humanos.',
        subject: 'direitos_humanos',
      },
      {
        id: 'sm5',
        text: 'Julgue: O princípio da autotutela permite à Administração anular seus atos ilegais independentemente de intervenção do Poder Judiciário.',
        options: ['Certo', 'Errado'],
        correctIndex: 0,
        explanation: 'CERTO (Dir. Adm.). Autotutela: a Administração pode ANULAR atos ilegais e REVOGAR atos inoportunos de ofício, sem precisar de ordem judicial. Súmula 473/STF.',
        subject: 'administrativo',
      },
      {
        id: 'sm6',
        text: 'No Excel, qual fórmula calcula a média dos valores nas células A1 a A10?',
        options: ['=SOMA(A1:A10)/10', '=MÉDIA(A1:A10)', '=CALC(A1:A10)', 'Ambas a e b estão corretas'],
        correctIndex: 3,
        explanation: '(Informática) Tanto =MÉDIA(A1:A10) quanto =SOMA(A1:A10)/10 produzem o mesmo resultado — a média aritmética. A função =CALC não existe no Excel.',
        subject: 'informatica',
      },
      {
        id: 'sm7',
        text: 'Em uma via pública, dois veículos chegam ao mesmo tempo a um cruzamento sem sinalização. O veículo A vem pela esquerda de B. Quem tem preferência?',
        options: ['Veículo A', 'Veículo B', 'O maior', 'Nenhum — ambos param'],
        correctIndex: 1,
        explanation: '(CTB) Veículo B tem preferência, pois vem pela DIREITA de A. Art. 29, III, a do CTB: prioridade ao veículo que vem pela direita.',
        subject: 'ctb',
      },
      {
        id: 'sm8',
        text: 'Vírus difere de Worm porque:',
        options: [
          'Vírus criptografa arquivos; Worm rouba senhas.',
          'Vírus precisa de hospedeiro para se propagar; Worm se propaga sozinho.',
          'Vírus é indetectável; Worm deixa rastros.',
          'Não há diferença entre eles.',
        ],
        correctIndex: 1,
        explanation: '(Informática) Vírus depende de arquivo hospedeiro para se replicar e propagar. Worm se auto-replica e se propaga automaticamente pela rede, sem precisar de um hospedeiro.',
        subject: 'informatica',
      },
      {
        id: 'sm9',
        text: 'O Pacto de São José da Costa Rica é o nome popular da:',
        options: [
          'Declaração Universal dos Direitos Humanos',
          'Carta das Nações Unidas',
          'Convenção Americana sobre Direitos Humanos',
          'Convenção de Viena',
        ],
        correctIndex: 2,
        explanation: 'O Pacto de São José da Costa Rica é o nome pelo qual ficou conhecida a Convenção Americana sobre Direitos Humanos, assinada em São José, Costa Rica, em 1969.',
        subject: 'direitos_humanos',
      },
      {
        id: 'sm10',
        text: 'Julgue: Dirigir com CNH suspensa é crime previsto no Código de Trânsito Brasileiro.',
        options: ['Certo', 'Errado'],
        correctIndex: 0,
        explanation: 'CERTO. O art. 307 do CTB tipifica como crime a violação da suspensão ou proibição de se obter a permissão ou a habilitação para dirigir veículo, com pena de detenção de 6 meses a 1 ano e multa.',
        subject: 'ctb',
      },
    ],
  },
];
