import type { Post, Subject, Simulado, Comment, Notification } from "./types";

export const MOCK_POSTS: Post[] = [
  {
    id: "post_1",
    authorId: "instrutor_1",
    authorName: "Instrutor Silva",
    authorPhoto: "",
    authorRole: "instrutor",
    title: "📌 Edital PRF 2025 – Tudo que você precisa saber",
    text: "O edital do concurso da PRF para 2025 foi publicado com 2.500 vagas para Policial Rodoviário Federal. O cargo exige curso superior em qualquer área. As inscrições serão realizadas pelo site do CEBRASPE. Confira os detalhes completos abaixo e prepare-se para essa oportunidade!",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    isPinned: true,
    type: "novidades",
    likes: 284,
    likedBy: [],
    commentCount: 47,
    savedBy: [],
    reportedBy: [],
  },
  {
    id: "post_2",
    authorId: "instrutor_2",
    authorName: "Prof. Carvalho",
    authorPhoto: "",
    authorRole: "instrutor",
    title: "📌 Cronograma Oficial de Estudos – Novembro 2025",
    text: "Segue o cronograma atualizado para os próximos 30 dias focando nas matérias mais cobradas no concurso da PRF. Prioridade: Legislação de Trânsito (35% das questões), Direito Constitucional (20%) e Raciocínio Lógico (15%). Siga à risca e garanta aprovação!",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: true,
    type: "novidades",
    likes: 193,
    likedBy: [],
    commentCount: 28,
    savedBy: [],
    reportedBy: [],
  },
  {
    id: "post_3",
    authorId: "instrutor_1",
    authorName: "Instrutor Silva",
    authorPhoto: "",
    authorRole: "instrutor",
    title: "Dica de Estudo: Legislação de Trânsito em 30 dias",
    text: "Muitos candidatos têm dificuldade com o CTB. A dica principal é: leia o Código de Trânsito Brasileiro completo pelo menos 2 vezes. Depois, resolva questões por assunto. O CEBRASPE gosta de cobrar infrações, penalidades e normas de circulação. Foco total!",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    type: "novidades",
    likes: 156,
    likedBy: [],
    commentCount: 34,
    savedBy: [],
    reportedBy: [],
  },
  {
    id: "post_4",
    authorId: "instrutor_2",
    authorName: "Prof. Carvalho",
    authorPhoto: "",
    authorRole: "instrutor",
    title: "TAF 2025: Atualização nos critérios de avaliação",
    text: "O Teste de Aptidão Física passou por atualizações importantes. Para homens: corrida de 12 minutos (mínimo 2.400m), barra fixa (mínimo 6 repetições). Para mulheres: corrida de 12 minutos (mínimo 2.100m), flexão de braço (mínimo 20 repetições). Treinem com consistência!",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    type: "novidades",
    likes: 312,
    likedBy: [],
    commentCount: 89,
    savedBy: [],
    reportedBy: [],
  },
  {
    id: "post_5",
    authorId: "instrutor_1",
    authorName: "Instrutor Silva",
    authorPhoto: "",
    authorRole: "instrutor",
    title: "Direito Constitucional: Os temas mais cobrados",
    text: "Baseado nas últimas provas da PRF, os temas mais cobrados em Direito Constitucional são: Direitos e Garantias Fundamentais (Art. 5°), Administração Pública (Art. 37-41), Poder Executivo e Organização do Estado. Domine esses tópicos e você já tem 70% da matéria!",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    type: "novidades",
    likes: 445,
    likedBy: [],
    commentCount: 62,
    savedBy: [],
    reportedBy: [],
  },
];

export const MOCK_COMMUNITY_POSTS: Post[] = [
  {
    id: "comm_1",
    authorId: "user_demo1",
    authorName: "@Leivison_7",
    authorPhoto: "",
    authorRole: "usuario",
    title: "Como vocês estudam Direito Constitucional?",
    text: "Estou tendo muita dificuldade com essa matéria. Alguém tem dica de método de estudo ou material bom? Já li o livro do Prof. Novelino mas acho que preciso de algo mais prático.",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    type: "comunidade",
    likes: 35,
    likedBy: [],
    commentCount: 12,
    savedBy: [],
    reportedBy: [],
  },
  {
    id: "comm_2",
    authorId: "user_demo2",
    authorName: "@Ana_Candidata",
    authorPhoto: "",
    authorRole: "usuario",
    title: "Resultado do meu primeiro simulado!",
    text: "Finalmente consegui tirar 70% no simulado de Legislação de Trânsito! Foram 3 semanas estudando intensivamente. Para quem está começando: não desistam, o resultado vem com consistência. Sigam em frente! 💪",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    type: "comunidade",
    likes: 87,
    likedBy: [],
    commentCount: 23,
    savedBy: [],
    reportedBy: [],
  },
  {
    id: "comm_3",
    authorId: "user_demo3",
    authorName: "@Carlos_Estudante",
    authorPhoto: "",
    authorRole: "usuario",
    title: "Dica para o TAF: Protocolo de treino que funcionou pra mim",
    text: "Depois de 4 meses treinando, consegui bater a meta do TAF com folga. Corria 5x por semana alternando intervalado e longo. A chave é a consistência e não exagerar no início. Vou postar meu treino completo se tiverem interesse!",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    isPinned: false,
    type: "comunidade",
    likes: 124,
    likedBy: [],
    commentCount: 41,
    savedBy: [],
    reportedBy: [],
  },
];

export const MOCK_COMMENTS: Comment[] = [
  {
    id: "c1",
    postId: "post_3",
    authorId: "user_demo1",
    authorName: "@Leivison_7",
    authorPhoto: "",
    text: "Excelente dica! Já estou no segundo capítulo do CTB. Muito mais fácil de entender assim.",
    likes: 12,
    likedBy: [],
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "c2",
    postId: "post_3",
    authorId: "user_demo2",
    authorName: "@Ana_Candidata",
    authorPhoto: "",
    text: "Quanto tempo levou para ler o CTB completo? Estou tentando fazer isso em 2 semanas.",
    likes: 5,
    likedBy: [],
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: "portugues",
    name: "Língua Portuguesa",
    icon: "book-open",
    color: "#3B82F6",
    topics: [
      { id: "port-interpretacao", name: "Interpretação de Texto" },
      { id: "port-coesao",        name: "Coesão e Coerência Textual" },
      { id: "port-morfologia",    name: "Classes de Palavras (Morfologia)" },
      { id: "port-sintaxe",       name: "Sintaxe: Concordância e Regência" },
      { id: "port-crase",         name: "Crase" },
      { id: "port-pontuacao",     name: "Pontuação" },
    ],
  },
  {
    id: "raciocinio-logico",
    name: "Raciocínio Lógico",
    icon: "cpu",
    color: "#8B5CF6",
    topics: [
      { id: "rl-proposicoes",         name: "Proposições e Conectivos Lógicos" },
      { id: "rl-negacao",             name: "Negação e Equivalência Lógica" },
      { id: "rl-probabilidade",       name: "Probabilidade" },
      { id: "rl-combinatoria",        name: "Combinatória e Contagem" },
      { id: "rl-raciocinio-sequencias", name: "Sequências e Progressões" },
    ],
  },
  {
    id: "legislacao-transito",
    name: "Legislação de Trânsito",
    icon: "navigation",
    color: "#EF4444",
    topics: [
      { id: "ctb-snf",        name: "Sistema Nacional de Trânsito (SNT)" },
      { id: "ctb-circulacao", name: "Circulação, Via e Sinalização" },
      { id: "ctb-infracoes",  name: "Infrações e Penalidades" },
      { id: "ctb-crimes",     name: "Crimes de Trânsito (Arts. 302 a 312)" },
      { id: "ctb-habilitacao",name: "Habilitação de Condutores (CNH)" },
      { id: "ctb-alcool",     name: "Álcool e Direção" },
    ],
  },
  {
    id: "fisica",
    name: "Física Aplicada ao Trânsito",
    icon: "zap",
    color: "#F59E0B",
    topics: [
      { id: "fis-cinematica",       name: "Cinemática: Conceitos Básicos" },
      { id: "fis-mruv",             name: "MRUV e Frenagem" },
      { id: "fis-reacao-frenagem",  name: "Tempo de Reação e Distância de Parada" },
      { id: "fis-energia-colisao",  name: "Energia Cinética e Colisões" },
      { id: "fis-forcas",           name: "Leis de Newton Aplicadas" },
    ],
  },
  {
    id: "dir-administrativo",
    name: "Direito Administrativo",
    icon: "briefcase",
    color: "#10B981",
    topics: [
      { id: "da-principios",     name: "Princípios da Administração Pública" },
      { id: "da-atos",           name: "Atos Administrativos" },
      { id: "da-licitacao",      name: "Licitações (Lei 14.133/2021)" },
      { id: "da-agentes",        name: "Agentes Públicos e Servidores" },
      { id: "da-responsabilidade",name: "Responsabilidade Civil do Estado" },
      { id: "da-improbidade",    name: "Improbidade Administrativa" },
    ],
  },
  {
    id: "dir-constitucional",
    name: "Direito Constitucional",
    icon: "shield",
    color: "#6366F1",
    topics: [
      { id: "dc-principios",  name: "Princípios Fundamentais (Arts. 1º a 4º)" },
      { id: "dc-direitos",    name: "Direitos e Garantias Fundamentais (Art. 5°)" },
      { id: "dc-remedios",    name: "Remédios Constitucionais" },
      { id: "dc-segpublica",  name: "Segurança Pública (Art. 144)" },
      { id: "dc-controle",    name: "Controle de Constitucionalidade" },
    ],
  },
  {
    id: "dir-penal",
    name: "Direito Penal",
    icon: "alert-triangle",
    color: "#DC2626",
    topics: [
      { id: "dp-teoria-crime",  name: "Teoria do Crime" },
      { id: "dp-iter",          name: "Iter Criminis e Tentativa" },
      { id: "dp-crimes-especie",name: "Crimes Contra a Pessoa e o Patrimônio" },
      { id: "dp-crimes-adm",    name: "Crimes Contra a Administração Pública" },
      { id: "dp-hediondos",     name: "Crimes Hediondos (Lei 8.072/90)" },
    ],
  },
  {
    id: "dir-processual-penal",
    name: "Processo Penal",
    icon: "file-text",
    color: "#7C3AED",
    topics: [
      { id: "dpp-inquerito", name: "Inquérito Policial" },
      { id: "dpp-provas",    name: "Provas no Processo Penal" },
      { id: "dpp-prisoes",   name: "Prisões e Medidas Cautelares" },
    ],
  },
  {
    id: "legislacao-especial",
    name: "Legislação Especial PRF",
    icon: "flag",
    color: "#059669",
    topics: [
      { id: "le-lei-prf",          name: "Lei Orgânica e Estatuto da PRF" },
      { id: "le-drogas",           name: "Lei de Drogas (Lei 11.343/2006)" },
      { id: "le-abuso-autoridade", name: "Lei de Abuso de Autoridade (Lei 13.869/2019)" },
      { id: "le-estatuto-crianca", name: "ECA — Estatuto da Criança e do Adolescente" },
      { id: "le-interceptacao",    name: "Interceptação Telefônica (Lei 9.296/1996)" },
    ],
  },
  {
    id: "direitos-humanos",
    name: "Direitos Humanos",
    icon: "users",
    color: "#F97316",
    topics: [
      { id: "dh-conceito",              name: "Conceito e Gerações de Direitos" },
      { id: "dh-dudh",                  name: "Declaração Universal dos DH (1948)" },
      { id: "dh-sistema-interamericano",name: "Sistema Interamericano de Proteção" },
      { id: "dh-atividade-policial",    name: "Direitos Humanos e Atividade Policial" },
    ],
  },
  {
    id: "informatica",
    name: "Informática",
    icon: "monitor",
    color: "#0EA5E9",
    topics: [
      { id: "inf-hardware",     name: "Hardware: Componentes e Periféricos" },
      { id: "inf-windows",      name: "Sistemas Operacionais (Windows e Linux)" },
      { id: "inf-pacote-office",name: "Microsoft Office (Word, Excel, PowerPoint)" },
      { id: "inf-internet",     name: "Internet, Navegadores e Redes" },
    ],
  },
];

export const MOCK_SIMULADOS: Simulado[] = [
  {
    id: "simulado_1",
    title: "Simulado 01 – Legislação de Trânsito",
    description: "10 questões sobre o Código de Trânsito Brasileiro",
    timeLimit: 15,
    questions: [
      {
        id: "q1",
        text: "De acordo com o CTB, o que é considerado infração de trânsito?",
        options: [
          "Apenas ações que causem danos materiais",
          "A inobservância de qualquer preceito do CTB, resoluções e normas de trânsito",
          "Somente atos que coloquem em risco a vida humana",
          "Apenas infrações cometidas por condutores habilitados",
        ],
        correctIndex: 1,
        explanation:
          "Segundo o Art. 161 do CTB, infração é a inobservância de qualquer preceito do Código de Trânsito Brasileiro, das resoluções do CONTRAN e dos dispositivos de regulamentação.",
      },
      {
        id: "q2",
        text: "Qual a velocidade máxima permitida em rodovias federais para automóveis, segundo o CTB?",
        options: ["80 km/h", "100 km/h", "110 km/h", "120 km/h"],
        correctIndex: 2,
        explanation:
          "O Art. 61 do CTB estabelece que a velocidade máxima em rodovias para automóveis e camionetas é de 110 km/h.",
      },
      {
        id: "q3",
        text: "Dirigir com CNH vencida há mais de 30 dias é considerada infração de que natureza?",
        options: ["Leve", "Média", "Grave", "Gravíssima"],
        correctIndex: 3,
        explanation:
          "Conforme o Art. 162, I do CTB, dirigir sem possuir CNH ou com CNH vencida é infração gravíssima, sujeita a multa e apreensão do veículo.",
      },
      {
        id: "q4",
        text: "O que é a 'suspensão do direito de dirigir' no CTB?",
        options: [
          "Penalidade aplicada automaticamente quando o condutor comete qualquer infração",
          "Penalidade que proíbe o condutor de dirigir por determinado período",
          "Cassação definitiva da CNH",
          "Medida administrativa aplicada apenas para crimes de trânsito",
        ],
        correctIndex: 1,
        explanation:
          "A suspensão do direito de dirigir é uma penalidade prevista no Art. 256 do CTB que proíbe o infrator de obter ou usar a CNH por período de 1 a 12 meses.",
      },
      {
        id: "q5",
        text: "Qual órgão máximo normativo e consultivo do Sistema Nacional de Trânsito?",
        options: [
          "DENATRAN",
          "DNIT",
          "CONTRAN",
          "Polícia Rodoviária Federal",
        ],
        correctIndex: 2,
        explanation:
          "O CONTRAN (Conselho Nacional de Trânsito) é o órgão máximo normativo e consultivo do SNT, conforme o Art. 7° do CTB.",
      },
      {
        id: "q6",
        text: "Segundo o CTB, é obrigatório o uso do cinto de segurança:",
        options: [
          "Apenas em rodovias federais",
          "Apenas pelo motorista e passageiro do banco dianteiro",
          "Por todos os ocupantes do veículo em qualquer via",
          "Apenas em vias urbanas com velocidade acima de 60 km/h",
        ],
        correctIndex: 2,
        explanation:
          "O Art. 65 do CTB determina que é obrigatório o uso do cinto de segurança para o condutor e passageiros em todas as vias.",
      },
      {
        id: "q7",
        text: "Quantos pontos acumula em 12 meses resultam em suspensão da CNH, para condutor de veículo de passeio?",
        options: ["15 pontos", "20 pontos", "30 pontos", "40 pontos"],
        correctIndex: 2,
        explanation:
          "Conforme a Resolução CONTRAN n° 809/2020, o condutor que acumular 30 pontos ou mais em 12 meses terá a CNH suspensa (para condutores sem histórico de suspensão).",
      },
      {
        id: "q8",
        text: "A Polícia Rodoviária Federal tem como atribuição:",
        options: [
          "Policiamento ostensivo apenas em rodovias estaduais",
          "Patrulhamento ostensivo das rodovias federais",
          "Apenas aplicação de multas de trânsito",
          "Gerenciar o registro de veículos no DETRAN",
        ],
        correctIndex: 1,
        explanation:
          "A PRF tem como principal atribuição constitucional o patrulhamento ostensivo das rodovias federais, conforme o Art. 144, II da Constituição Federal.",
      },
      {
        id: "q9",
        text: "O que é 'estacionamento' segundo o CTB?",
        options: [
          "Imobilização do veículo por tempo indefinido para qualquer finalidade",
          "Imobilização do veículo por tempo superior ao necessário para embarque/desembarque",
          "Parada do veículo por até 5 minutos",
          "Qualquer parada de veículo em via pública",
        ],
        correctIndex: 1,
        explanation:
          "Segundo o Art. 2°, XIV do CTB, estacionamento é a imobilização de veículos por tempo superior ao necessário para embarque ou desembarque de passageiros.",
      },
      {
        id: "q10",
        text: "Qual a penalidade para quem dirigir sob influência de álcool com concentração igual ou superior a 6 decigramas por litro de sangue?",
        options: [
          "Multa e suspensão da CNH",
          "Detenção de 6 meses a 3 anos, multa e suspensão da CNH",
          "Apenas multa administrativa",
          "Reclusão de 2 a 5 anos",
        ],
        correctIndex: 1,
        explanation:
          "O Art. 306 do CTB prevê crime para quem conduzir sob influência de álcool com CBAs ≥ 6dg/L: detenção de 6 meses a 3 anos, multa e suspensão da CNH.",
      },
    ],
  },
  {
    id: "simulado_2",
    title: "Simulado 02 – Direito Constitucional",
    description: "10 questões sobre a Constituição Federal",
    timeLimit: 15,
    questions: [
      {
        id: "q2_1",
        text: "De acordo com a CF/88, são objetivos fundamentais da República Federativa do Brasil, EXCETO:",
        options: [
          "Construir uma sociedade livre, justa e solidária",
          "Garantir o desenvolvimento nacional",
          "Promover o bem de todos, sem preconceitos",
          "Manter a soberania e a independência nacional como objetivo principal",
        ],
        correctIndex: 3,
        explanation:
          "Os objetivos fundamentais estão no Art. 3° da CF/88. A soberania é um fundamento (Art. 1°), não um objetivo fundamental.",
      },
      {
        id: "q2_2",
        text: "Segundo o Art. 5° da CF/88, é VEDADO:",
        options: [
          "A liberdade de expressão intelectual e artística",
          "A criação de associações para fins lícitos",
          "Tribunais e juízos de exceção",
          "A inviolabilidade do domicílio",
        ],
        correctIndex: 2,
        explanation:
          "O Art. 5°, XXXVII da CF/88 veda expressamente a criação de juízo ou tribunal de exceção.",
      },
      {
        id: "q2_3",
        text: "O princípio da legalidade na Administração Pública significa que:",
        options: [
          "O administrador pode fazer tudo que a lei não proíbe",
          "O administrador só pode fazer o que a lei autoriza",
          "A lei é aplicada somente quando benéfica ao cidadão",
          "Os atos administrativos não precisam de previsão legal",
        ],
        correctIndex: 1,
        explanation:
          "Na Administração Pública o princípio da legalidade é estrito: o agente só pode agir quando houver previsão legal autorizando, diferente do particular que pode fazer tudo o que não é proibido.",
      },
      {
        id: "q2_4",
        text: "Qual o prazo do Habeas Corpus para proteger a liberdade de locomoção?",
        options: [
          "É imprescritível e pode ser impetrado a qualquer tempo",
          "30 dias após a ameaça ou coação",
          "5 anos, por analogia à prescrição administrativa",
          "120 dias, como o mandado de segurança",
        ],
        correctIndex: 0,
        explanation:
          "O Habeas Corpus é imprescritível. Pode ser impetrado a qualquer tempo enquanto existir a ameaça ou coação ilegal à liberdade de locomoção.",
      },
      {
        id: "q2_5",
        text: "A segurança pública é dever do Estado e direito e responsabilidade de:",
        options: [
          "Apenas dos órgãos policiais",
          "Apenas do Governo Federal",
          "Todos",
          "Apenas dos estados e DF",
        ],
        correctIndex: 2,
        explanation:
          "O Art. 144 da CF/88 estabelece que a segurança pública é dever do Estado e direito e responsabilidade de todos, exercida para a preservação da ordem pública.",
      },
      {
        id: "q2_6",
        text: "A Polícia Rodoviária Federal está prevista na Constituição Federal em qual artigo?",
        options: ["Art. 142", "Art. 143", "Art. 144", "Art. 145"],
        correctIndex: 2,
        explanation:
          "A PRF está prevista no Art. 144, II da CF/88, como órgão de segurança pública responsável pelo patrulhamento ostensivo das rodovias federais.",
      },
      {
        id: "q2_7",
        text: "O princípio da moralidade administrativa refere-se:",
        options: [
          "À obrigação de o administrador agir conforme a lei",
          "À exigência de comportamento ético, honesto e de boa-fé na Administração",
          "À obrigação de publicar todos os atos administrativos",
          "À isonomia no tratamento dos administrados",
        ],
        correctIndex: 1,
        explanation:
          "O princípio da moralidade (Art. 37 da CF) exige que o administrador aja com ética, boa-fé, honestidade e probidade, não bastando apenas a legalidade formal do ato.",
      },
      {
        id: "q2_8",
        text: "São direitos sociais previstos no Art. 6° da CF/88:",
        options: [
          "Vida, liberdade e segurança",
          "Educação, saúde, alimentação, trabalho, moradia e lazer",
          "Soberania, cidadania e dignidade da pessoa humana",
          "Igualdade, legalidade e contraditório",
        ],
        correctIndex: 1,
        explanation:
          "O Art. 6° da CF/88 lista os direitos sociais: educação, saúde, alimentação, trabalho, moradia, transporte, lazer, segurança, previdência social, proteção à maternidade e à infância e assistência aos desamparados.",
      },
      {
        id: "q2_9",
        text: "Qual o prazo máximo de duração do estado de defesa?",
        options: ["15 dias, prorrogável uma vez", "30 dias, prorrogável uma vez por igual período", "60 dias", "90 dias"],
        correctIndex: 1,
        explanation:
          "O Art. 136, §2° da CF/88 estabelece que o estado de defesa não excederá a 30 dias, podendo ser prorrogado uma única vez por igual período.",
      },
      {
        id: "q2_10",
        text: "A ação popular pode ser proposta por:",
        options: [
          "Qualquer pessoa física ou jurídica",
          "Apenas pelo Ministério Público",
          "Qualquer cidadão para anular ato lesivo ao patrimônio público",
          "Apenas por entidades de classe",
        ],
        correctIndex: 2,
        explanation:
          "O Art. 5°, LXXIII da CF/88 prevê que qualquer cidadão (eleitor) é parte legítima para propor ação popular visando anular ato lesivo ao patrimônio público, à moralidade administrativa, ao meio ambiente e ao patrimônio histórico.",
      },
    ],
  },
  {
    id: "simulado_3",
    title: "Simulado 03 – Raciocínio Lógico",
    description: "10 questões de lógica e raciocínio",
    timeLimit: 20,
    questions: [
      {
        id: "q3_1",
        text: "Se 'Todo policial é corajoso' e 'Pedro é policial', então:",
        options: [
          "Pedro pode ou não ser corajoso",
          "Pedro é corajoso",
          "Pedro não é corajoso",
          "Nada se pode concluir sobre Pedro",
        ],
        correctIndex: 1,
        explanation:
          "Silogismo válido: Premissa maior (Todo policial é corajoso) + Premissa menor (Pedro é policial) = Conclusão (Pedro é corajoso). Modus Ponens.",
      },
      {
        id: "q3_2",
        text: "Qual o próximo número da sequência: 2, 6, 18, 54, ___?",
        options: ["108", "162", "216", "324"],
        correctIndex: 1,
        explanation:
          "A razão entre termos consecutivos é 3 (sequência geométrica de razão 3). Portanto: 54 × 3 = 162.",
      },
      {
        id: "q3_3",
        text: "A negação de 'Todos os candidatos passaram na prova' é:",
        options: [
          "Nenhum candidato passou na prova",
          "Alguns candidatos passaram na prova",
          "Pelo menos um candidato não passou na prova",
          "A maioria dos candidatos não passou na prova",
        ],
        correctIndex: 2,
        explanation:
          "A negação de 'Todos os A são B' é 'Existe pelo menos um A que não é B' (Existe um candidato que não passou). Em lógica: ¬(∀x P(x)) ≡ ∃x ¬P(x).",
      },
      {
        id: "q3_4",
        text: "Em um grupo de 50 pessoas, 30 falam inglês e 25 falam espanhol. Se 10 falam ambos, quantos não falam nenhum dos dois idiomas?",
        options: ["5", "10", "15", "20"],
        correctIndex: 0,
        explanation:
          "Pelo princípio da inclusão-exclusão: |I ∪ E| = 30 + 25 - 10 = 45. Logo, os que não falam nenhum = 50 - 45 = 5.",
      },
      {
        id: "q3_5",
        text: "Se P → Q é verdadeiro e P é verdadeiro, então:",
        options: [
          "Q pode ser verdadeiro ou falso",
          "Q é necessariamente verdadeiro",
          "Q é necessariamente falso",
          "P é falso",
        ],
        correctIndex: 1,
        explanation:
          "Modus Ponens: Se P implica Q (P → Q = V) e P é verdadeiro, então Q é necessariamente verdadeiro.",
      },
      {
        id: "q3_6",
        text: "Quantos triângulos existem na figura de um triângulo dividido em 4 triângulos menores iguais (estrela de triângulo)?",
        options: ["4", "5", "6", "8"],
        correctIndex: 2,
        explanation:
          "Em um triângulo dividido em 4 partes iguais: 4 triângulos menores + 1 triângulo médio (formado por 3 menores) + 1 triângulo grande (total) = Mas a configuração clássica tem 5 triângulos menores visíveis + o grande = 5. A resposta correta para divisão em 4 triângulos é 5.",
      },
      {
        id: "q3_7",
        text: "Maria tem o dobro da idade de João. Daqui a 5 anos, a soma das idades deles será 40. Qual a idade atual de Maria?",
        options: ["15", "20", "18", "10"],
        correctIndex: 1,
        explanation:
          "Seja J = idade de João. M = 2J. (J+5) + (2J+5) = 40 → 3J + 10 = 40 → J = 10. M = 20.",
      },
      {
        id: "q3_8",
        text: "A contrapositiva de 'Se chove, então o chão fica molhado' é:",
        options: [
          "Se não chove, então o chão não fica molhado",
          "Se o chão não fica molhado, então não choveu",
          "Se o chão fica molhado, então choveu",
          "Não chove e o chão não fica molhado",
        ],
        correctIndex: 1,
        explanation:
          "A contrapositiva de P → Q é ¬Q → ¬P. Portanto: 'Se o chão não fica molhado (¬Q), então não choveu (¬P)'.",
      },
      {
        id: "q3_9",
        text: "Um agente percorre 60 km em 40 minutos. Qual sua velocidade média em km/h?",
        options: ["80 km/h", "90 km/h", "100 km/h", "120 km/h"],
        correctIndex: 1,
        explanation:
          "V = d/t = 60km / (40/60)h = 60 × (60/40) = 90 km/h.",
      },
      {
        id: "q3_10",
        text: "Se ABCD é um quadrado com lado 4, qual a área do maior círculo que cabe dentro do quadrado?",
        options: ["4π", "8π", "16π", "2π"],
        correctIndex: 0,
        explanation:
          "O maior círculo inscrito tem diâmetro igual ao lado do quadrado: d = 4, r = 2. Área = π × r² = π × 4 = 4π.",
      },
    ],
  },
  {
    id: "simulado_4",
    title: "Simulado 04 – Língua Portuguesa",
    description: "10 questões de interpretação, gramática e redação",
    timeLimit: 15,
    questions: [
      {
        id: "q4_1",
        text: "A frase 'Haviam muitos candidatos inscritos no concurso da PRF' está gramaticalmente correta?",
        options: [
          "Sim, pois o verbo 'haver' pode concordar com o sujeito",
          "Não, pois o verbo 'haver' no sentido de 'existir' é impessoal e não varia",
          "Sim, pois 'candidatos' é o sujeito da oração",
          "Não, pois o verbo deveria ser 'houveram'",
        ],
        correctIndex: 1,
        explanation: "O verbo 'haver' no sentido de 'existir' é impessoal — não tem sujeito e não varia: 'Havia muitos candidatos'. O mesmo se aplica a 'fazer' indicando tempo: 'Faz dois anos'.",
      },
      {
        id: "q4_2",
        text: "Em qual das alternativas o uso da crase está CORRETO?",
        options: [
          "O policial foi à pé até o local do acidente",
          "Ele se referiu à ela durante o depoimento",
          "O agente chegou à delegacia às 8 horas",
          "Vou à trabalhar amanhã cedo",
        ],
        correctIndex: 2,
        explanation: "'À delegacia' = prep. 'a' + artigo 'a' (delegacia é feminina e admite artigo). 'Às 8 horas' = hora determinada → crase obrigatória. 'À pé' está errado (pé é masculino); 'à ela' está errado (pronome pessoal); 'à trabalhar' está errado (verbo).",
      },
      {
        id: "q4_3",
        text: "O conectivo 'embora' estabelece relação de:",
        options: ["Causa", "Conclusão", "Concessão", "Condição"],
        correctIndex: 2,
        explanation: "'Embora' é conjunção concessiva — introduz uma oração que admite o que foi dito na oração anterior, mas apresenta algo contrário ao esperado. Ex: 'Embora estudasse muito, não foi aprovado'.",
      },
      {
        id: "q4_4",
        text: "Qual a negação correta de 'Todo policial é corajoso'?",
        options: [
          "Nenhum policial é corajoso",
          "Algum policial não é corajoso",
          "Alguns policiais são corajosos",
          "Nenhum policial é covarde",
        ],
        correctIndex: 1,
        explanation: "A negação de 'Todo A é B' é 'Algum A não é B' (ou 'Existe pelo menos um A que não é B'). Em lógica: ¬(∀x P(x)) ≡ ∃x ¬P(x).",
      },
      {
        id: "q4_5",
        text: "A vírgula está empregada INCORRETAMENTE em qual alternativa?",
        options: [
          "Pedro, o melhor candidato da turma, foi aprovado na PRF.",
          "Ao chegar ao local do acidente, o agente registrou a ocorrência.",
          "O policial rodoviário federal, fiscalizou a rodovia ontem.",
          "Estudou muito, portanto foi aprovado.",
        ],
        correctIndex: 2,
        explanation: "Separar sujeito ('O policial rodoviário federal') do verbo ('fiscalizou') com vírgula é proibido gramaticalmente. As demais alternativas estão corretas (aposto, oração adverbial anteposta, oração coordenada conclusiva).",
      },
      {
        id: "q4_6",
        text: "Qual a classe gramatical de 'onde' na frase 'A rodovia onde ocorreu o acidente foi sinalizada'?",
        options: ["Advérbio de lugar", "Pronome relativo", "Conjunção subordinativa", "Preposição"],
        correctIndex: 1,
        explanation: "'Onde' nessa frase é pronome relativo com antecedente 'rodovia' (lugar). Retoma o antecedente e une as orações. Quando não tem antecedente, é advérbio interrogativo ('Onde você está?').",
      },
      {
        id: "q4_7",
        text: "Em qual alternativa o verbo está empregado com a regência CORRETA?",
        options: [
          "O policial assistiu o julgamento até o final.",
          "O candidato aspira o cargo de Policial Rodoviário Federal.",
          "Todos devem obedecer às normas de trânsito.",
          "O servidor visa o bem da coletividade.",
        ],
        correctIndex: 2,
        explanation: "'Obedecer' exige a preposição 'a' — 'obedecer às normas' está correto. 'Assistir' (ver) exige 'a': 'assistiu ao julgamento'. 'Aspirar' (desejar) exige 'a': 'aspira ao cargo'. 'Visar' (almejar) exige 'a': 'visa ao bem'.",
      },
      {
        id: "q4_8",
        text: "O pronome relativo 'cujo' em 'O agente cujo relatório foi elogiado recebeu prêmio' concorda com:",
        options: ["O agente (antecedente)", "O relatório (possuído)", "Foi elogiado (verbo)", "Recebeu prêmio (oração principal)"],
        correctIndex: 1,
        explanation: "'Cujo' concorda com o POSSUÍDO (o que vem depois): 'relatório' é masculino singular → 'cujo' (masculino singular). Se fosse 'cujas funções', usaríamos 'cujas' (feminino plural).",
      },
      {
        id: "q4_9",
        text: "A frase 'O candidato não obteve a aprovação, mas continuou estudando' apresenta relação de:",
        options: ["Causa", "Conclusão", "Adversidade", "Concessão"],
        correctIndex: 2,
        explanation: "'Mas' é conjunção coordenativa adversativa — estabelece oposição ou contraste entre as orações coordenadas.",
      },
      {
        id: "q4_10",
        text: "Em 'Faz dois anos que não ocorrem acidentes neste trecho', o verbo 'fazer' está:",
        options: [
          "Correto, concordando com 'anos' no plural",
          "Incorreto, deveria ser 'fazem dois anos'",
          "Correto, pois é verbo impessoal indicando tempo",
          "Incorreto, deveria ser 'há dois anos'",
        ],
        correctIndex: 2,
        explanation: "O verbo 'fazer' indicando tempo decorrido é IMPESSOAL — não varia: 'Faz dois anos' (não 'fazem'). Da mesma forma, 'há dois anos' (verbo 'haver' no sentido de tempo = impessoal) também seria correto, mas a alternativa C está correta para a forma 'faz'.",
      },
    ],
  },
  {
    id: "simulado_5",
    title: "Simulado 05 – Direito Administrativo",
    description: "10 questões sobre princípios, atos e responsabilidade do Estado",
    timeLimit: 15,
    questions: [
      {
        id: "q5_1",
        text: "Qual princípio da Administração Pública foi acrescentado pela Emenda Constitucional n° 19/1998?",
        options: ["Legalidade", "Impessoalidade", "Moralidade", "Eficiência"],
        correctIndex: 3,
        explanation: "A EC 19/1998 acrescentou o princípio da Eficiência ao art. 37 da CF. Antes, os princípios expressos eram apenas LIMP (Legalidade, Impessoalidade, Moralidade e Publicidade).",
      },
      {
        id: "q5_2",
        text: "Quanto à extinção dos atos administrativos, é correto afirmar que:",
        options: [
          "A revogação desfaz atos ilegais com efeito retroativo",
          "A anulação desfaz atos por razões de conveniência com efeito ex nunc",
          "A revogação desfaz atos válidos por razões de mérito com efeito ex nunc",
          "A anulação e a revogação produzem os mesmos efeitos jurídicos",
        ],
        correctIndex: 2,
        explanation: "Revogação: ato válido, razões de conveniência/oportunidade (mérito), efeitos EX NUNC (não retroativos). Anulação: ato inválido (ilegal), efeitos EX TUNC (retroativos, desfaz desde a origem).",
      },
      {
        id: "q5_3",
        text: "Sobre a responsabilidade civil do Estado, é correto afirmar que:",
        options: [
          "O Estado responde subjetivamente pelos danos causados por seus agentes",
          "O Estado responde objetivamente, sendo necessário apenas comprovar o dano e o nexo causal",
          "O agente público responde objetivamente perante a vítima",
          "A responsabilidade do Estado só ocorre em caso de dolo do agente",
        ],
        correctIndex: 1,
        explanation: "Art. 37, §6° CF: o Estado responde OBJETIVAMENTE (independe de culpa ou dolo do agente), bastando a vítima provar a conduta, o dano e o nexo causal. O AGENTE responde subjetivamente (dolo ou culpa) em ação de regresso.",
      },
      {
        id: "q5_4",
        text: "A modalidade licitatória obrigatória para a contratação de bens e serviços comuns, preferencialmente na forma eletrônica, é:",
        options: ["Concorrência", "Pregão", "Concurso", "Diálogo competitivo"],
        correctIndex: 1,
        explanation: "Conforme a Lei 14.133/2021, o Pregão é a modalidade obrigatória para bens e serviços comuns, devendo ser realizado preferencialmente na forma eletrônica.",
      },
      {
        id: "q5_5",
        text: "A dispensa de licitação difere da inexigibilidade porque:",
        options: [
          "Na dispensa, a licitação é inviável; na inexigibilidade, é possível mas dispensada",
          "Na inexigibilidade, a competição é inviável; na dispensa, é possível mas dispensada",
          "Ambas ocorrem quando a competição é impossível",
          "A inexigibilidade está sujeita a valores; a dispensa não",
        ],
        correctIndex: 1,
        explanation: "DISPENSA: a competição SERIA possível, mas o legislador optou por dispensá-la (por valor, emergência etc.). INEXIGIBILIDADE: a competição é INVIÁVEL (fornecedor exclusivo, objeto singular, artista consagrado).",
      },
      {
        id: "q5_6",
        text: "O princípio da autotutela administrativa significa que:",
        options: [
          "A Administração pode sempre revogar atos que causem prejuízo ao particular",
          "Apenas o Judiciário pode anular atos administrativos ilegais",
          "A Administração pode revogar atos válidos por conveniência e anular atos ilegais, de ofício",
          "O particular pode contestar atos administrativos diretamente na esfera administrativa",
        ],
        correctIndex: 2,
        explanation: "Autotutela (Súmulas 346 e 473 do STF): a Administração pode, de ofício, revogar atos válidos por razões de mérito (conveniência/oportunidade) e anular atos ilegais. Não precisa recorrer ao Judiciário para isso.",
      },
      {
        id: "q5_7",
        text: "Conforme a Lei 14.230/2021 (reforma da Lei de Improbidade), para configurar ato de improbidade administrativa é necessário:",
        options: [
          "Culpa grave do agente público",
          "Qualquer irregularidade, ainda que não dolosa",
          "Dolo do agente público",
          "Mero descumprimento de norma administrativa",
        ],
        correctIndex: 2,
        explanation: "A Lei 14.230/2021 exige DOLO para qualquer modalidade de improbidade administrativa. A culpa não configura mais improbidade — representa uma mudança radical em relação à lei anterior.",
      },
      {
        id: "q5_8",
        text: "Para adquirir estabilidade no serviço público, o servidor efetivo deve:",
        options: [
          "Ser aprovado em concurso público e tomar posse no cargo",
          "Cumprir estágio probatório de 2 anos e ser aprovado em avaliação",
          "Cumprir 3 anos de efetivo exercício e ser aprovado em avaliação especial de desempenho",
          "Completar 5 anos no serviço público federal",
        ],
        correctIndex: 2,
        explanation: "Art. 41 CF (com redação da EC 19/98): o servidor nomeado para cargo de provimento efetivo adquire estabilidade após 3 anos de efetivo exercício, condicionada à aprovação em avaliação especial de desempenho.",
      },
      {
        id: "q5_9",
        text: "Qual dos elementos a seguir NÃO é elemento (requisito de validade) do ato administrativo?",
        options: ["Competência", "Finalidade", "Economicidade", "Objeto"],
        correctIndex: 2,
        explanation: "Os cinco elementos do ato administrativo são: Competência, Finalidade, Forma, Motivo e Objeto (COMFIMO). Economicidade é princípio do controle (art. 70 CF), não elemento do ato.",
      },
      {
        id: "q5_10",
        text: "A atribuição de presunção de legitimidade ao ato administrativo significa que:",
        options: [
          "O ato é definitivo e não pode ser contestado",
          "O ato é presumido legal até que se prove o contrário, cabendo ao particular o ônus da prova",
          "O ato só pode ser revogado por lei",
          "Qualquer ato administrativo é imune a controle judicial",
        ],
        correctIndex: 1,
        explanation: "Presunção de legitimidade: os atos administrativos são presumidos legais até que se prove o contrário. O ônus de provar a ilegalidade recai sobre quem alega. Não é presunção absoluta — é iuris tantum (relativa).",
      },
    ],
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    type: "new_post",
    title: "Nova publicação",
    body: "Instrutor Silva publicou: 'Dica de Estudo: Legislação de Trânsito em 30 dias'",
    fromUserName: "Instrutor Silva",
    fromUserPhoto: "",
    postId: "post_3",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: false,
  },
  {
    id: "n2",
    type: "like",
    title: "Curtida recebida",
    body: "@Leivison_7 curtiu seu comentário",
    fromUserName: "@Leivison_7",
    fromUserPhoto: "",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    isRead: false,
  },
  {
    id: "n3",
    type: "system",
    title: "Bem-vindo ao Project P.R.F!",
    body: "Complete seu cronograma de estudos e faça seu primeiro simulado hoje!",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    isRead: true,
  },
];
